<?php
/**
 * @file
 * Module file to alter site settings.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function page_json_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('system.site');
  if ($form_id === 'system_site_information_settings') {
    // Setting up the textfield for api key.
    $form['siteapikey'] = array(
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#description' => t('Enter site api key.'),
      '#default_value' => !empty($config->get('siteapikey')) ? $config->get('siteapikey') : 'No API Key yet',
    );
    // Register submit hander.
    $form['actions']['submit']['#submit'][] = 'page_json_submit_handler';
    // Changing submit button value.
    $form['actions']['submit']['#value'] = t('Update Configuration');
  }
}

/**
 * Submit handler for site.
 * @param  array $form
 * @param  FormStateInterface $form_state
 */
function page_json_submit_handler(array $form, FormStateInterface $form_state) {
  // Get value of api key from textfield.
  $api_key = $form_state->getValue('siteapikey');
  $config = \Drupal::configFactory()->getEditable('system.site');
  // Set value of api key to configuration.
  $config->set('siteapikey', $api_key);
  $config->save();
  drupal_set_message(t('Site API key has been saved with the value @siteapikey', array('@siteapikey' => $api_key)));
}
